### ISSUE TITLE
Errors in example

### ISSUE THREAD

**Issue by spassvogel** [loilo-inc/easeljs-react#2]
Hi, I tried to run your code but got greeted by a lot of errors..

![image](https://user-images.githubusercontent.com/985892/49731911-1e0bc700-fc7d-11e8-9882-d50a4cb81e47.png)

**Comment by keroxp** [comment]
What did you do to run example on you browser?
I tried to reproduce errors but cannot get it.

if you installed packages via npm, try yarn install. Packages with different version might be installed and something went wrong.

**Comment by spassvogel** [comment]
That must be it. I used npm only. Sorry about that.
